config/routes.rb
Rails.application.routes.draw do

  devise_for :fans
  resources :dishes
  resources :my_dishes
  
  root to: "dishes#index"

end

app/models/dish.rb
class Dish < ActiveRecord::Base
	validates :title, :description, presence: true
	validates :cost, numericality: {greater_than: 0, allow_nil: true}
	validates :pax, numericality: { only_integer: true, allow_nil: true, greater_than: 0}

	belongs_to :fan

	scope :search_by, ->(keyword){ where("title ILIKE ? OR description ILIKE ?", "%#{keyword}%", "%#{keyword}%")}
	scope :published, ->{ where(published: true) }
end

app/models/fan.rb
class Fan < ActiveRecord::Base
  has_many :dishes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
  			 :registerable, 
  			 :rememberable, 
  			 :trackable, 
  			 :validatable, 
  			 :confirmable
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :title, :description, presence: true
	validates :cost, presence: true, numericality: {greater_than: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

	before_action :authenticate_fan!, except: [:index, :show]

	def index
		@dishes = Dish.all.published

		if search_keyword
			@keyword = search_keyword
			@dishes = @dishes.search_by(@keyword)
		end
	end

	def show
		@dish = Dish.find(dish_id) 
	end

	# def new
	# 	@dish = Dish.new
	# end

	# def create
	# 	@dish = Dish.new(dish_params)
	# 	if @dish.save
	# 		redirect_to dishes_url
	# 	else
	# 		render :new
	# 	end
	# end

	private

	def dish_id
		params.require(:id)
	end

	def search_keyword
		params[:search_form] && params[:search_form][:keyword]
	end

	def dish_params
		params.require(:dish).permit(:title, :description, :cost, :pax, :vegetarian, :fan_id)
	end
end

app/controllers/my_dishes_controller.rb
class MyDishesController < ApplicationController
	before_action :authenticate_fan!
  before_action :check_ownership_of_my_dish!, only: [:edit, :update]

  def index
    @my_dishes = Dish.where(fan_id: fan_id)
    @my_dishes = @my_dishes.order(title: :asc)
  end

  def new
    @my_dish = Dish.new
  end

  def create
    @my_dish = Dish.new(my_dish_params.merge(fan_id: fan_id))
    # @my_dish.published = true
    if @my_dish.save
      redirect_to my_dishes_url, notice: 'You have successfully created your dish!'
    else
      flash.now[:alert] = 'There is an error during creation, please try again.'
      render :new
    end
  end

  def edit
    @my_dish = get_my_dish
    render :new
  end

  def update
    @my_dish = get_my_dish
    if @my_dish.update(my_dish_params)
      flash[:notice] = "You have Successfully Update your dish"
      redirect_to my_dishes_url
    else
      flash.now[:alert] = "There's an error on updating, please try again."
      render :new
    end
  end

  private

  def dish_id
    params.require(:id)
  end

  def fan_id
    current_fan.id
  end

  def my_dish_params
    params.require(:dish).permit(:title, :description, :cost, :pax, :vegetarian, :fan_id, :published)
  end

  def get_my_dish
    @my_dish ||= Dish.find(dish_id)
  end

  def check_ownership_of_my_dish!
    if current_fan.id != get_my_dish.fan_id
      redirect_to my_dishes_url, notice: "You do not have the permission"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def format_date(date)
		date.strftime("%d-%m-%Y")
	end

	def boolean_to_text(boolean)
		boolean ? 'Yes' : 'No'
	end
end

app/views/dishes/index.html.slim
#dishes_list
	.container
		.row
			.col-md-12
				h1.page_title Dishes listing
		.row
			.col-md-12
				.search
					= form_tag('/dishes', :method => 'get', id: "search-form")
						= text_field_tag "search_form[keyword]", @keyword, placeholder: "search"
						= submit_tag "Search", :name => nil
				br
				.create_dish
					= link_to('Create a dish', new_my_dish_path, :class => "btn btn-info btn-lg")
		.row
			- if @dishes.any?
				- @dishes.each do |dish|
					.dish.col-md-3
						h2.title= link_to(dish.title, dish_path(dish))
						.description
							span Description: 
							= dish.description
						.create_date
							span Create date: 
							= dish.created_at.strftime("%d-%m-%Y")
						.actions
							= link_to('Detail', dish_path(dish), { :class => 'detail' })
			- else
				| No dishes found.

app/views/dishes/show.html.slim
#dish-show.container
	.row
		.col-md-12
			h1.page_title Dish detail
			h2.title= @dish.title
			.description
				span Description: 
				= @dish.description
			- if @dish.cost
				.cost Cost:  #{number_to_currency(@dish.cost)}
			- if @dish.pax
				.pax Pax: #{@dish.pax}
			.vegeterian Vegetarian: #{boolean_to_text(@dish.vegetarian)}
			.published Publish #{boolean_to_text(@dish.published)}
			p 
				i = 'Created ' + time_ago_in_words(@dish.created_at) + ' ago'
			br
			= link_to("Edit dish", edit_my_dish_path, :class => 'btn btn-default')
			= link_to("Back to dishes listing", dishes_url, :class => 'btn btn-default')

app/views/layouts/application.html.slim
doctype html
html
  head
    title Ramseyfan
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      .row
        .col-md-12
          = render partial: 'shared/menu'
      - if notice
        p.alert.alert-success #{ notice }
      - if alert  
        p.alert.alert-danger #{ alert } 
      = yield

app/views/my_dishes/_form_field.html.slim
.form-group
	= f.label field
	= f.text_field field, autofocus: true, :class => 'form-control'
	br
	= f.object.errors[field].inject {|messages, error| messages + " and " + error }

app/views/my_dishes/index.html.slim
#dishes_list
	.container
		.row
			.col-md-12
				h1.page_title My dishes
		.row
			- if @my_dishes.any?
				- @my_dishes.each do |dish|
					.dish.col-md-3
						h2.title= link_to(dish.title, dish_path(dish))
						.description
							span Description: 
							= dish.description
						.create_date
							span Create date: 
							= dish.created_at.strftime("%d-%m-%Y")
						.actions
							= link_to('Detail', dish_path(dish), { :class => 'detail' })
			- else
				| No my_dishes found.

app/views/my_dishes/new.html.slim
#dish_new
	.container
		h1.page_title Create/Edit dish
		.product_form.col-sm-9
			- url = @my_dish.new_record? ? my_dishes_path : my_dish_path(@my_dish)
  		= semantic_form_for @my_dish, url: url do |f|
				= render partial: 'form_field', locals: { f: f, field: :title }
				= render partial: 'form_field', locals: { f: f, field: :description }
				= render partial: 'form_field', locals: { f: f, field: :cost }
				= render partial: 'form_field', locals: { f: f, field: :pax }

				.form-group
					= f.label :vegetarian
					= f.check_box :vegetarian
				.form-group
					= f.label :published
					= f.check_box :published

				.form-group
					= f.submit "Submit", :class => "btn btn-default"
					= link_to("Back", my_dishes_path, :class => "btn btn-default")

app/views/shared/_menu.html.slim
ul.col-md-2.nav.nav-pills
  li.home = link_to 'Home', dishes_path
ul.nav.nav-pills.pull-right
  - if fan_signed_in?
    li.create_dish = link_to 'Create Dish', new_my_dish_path
    li.my_dishes = link_to 'My Dishes', my_dishes_path
    li.update_profile = link_to 'Update Profile', edit_fan_registration_path
    li.logout = link_to 'Logout', destroy_fan_session_path, method: :delete
  - else
    li.login = link_to "Sign in", new_fan_session_path
    li.sign_up = link_to 'Sign up', new_fan_registration_path